2.0
CircleCI-Public/Salesforce-sfdx-cli-orb pull request #13
Opened 2020-05-28 09:49 UTC by gmemstr

2020-06-08 17:20 UTC, KyleTryon requested changes

2020-06-08 17:20 UTC, KyleTryon commented on .circleci/config.yml
> +          defaultusername: gabriel@circleci.cpe
is it really .cpe?

2020-06-09 08:10 UTC, gmemstr commented on .circleci/config.yml
> +          defaultusername: gabriel@circleci.cpe
Yep! The username needs to be in the form of an email, but does not have to be a valid email or domain.

2020-06-09 13:17 UTC, KyleTryon approved these changes

2020-06-09 13:19 UTC, merged